# NumPy

Numeric Python

In [ ]:
list - collection of different type of elements -> [10,'goa',11.5]
- memory allocation is not continuous          id(10), id('goa')

array - collection of similar type of elements -> [10,20,30,99,16]
                                                    0  1  2
- memory allocation is continuous                2011, 2013, 2015, ...


In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 3.9 MB/s eta 0:00:00a 0:00:01


### 1 - Creating a vector

In [2]:
import numpy as np

In [4]:
# help(np)

In [5]:
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [6]:
print(type(v))

<class 'numpy.ndarray'>


In [7]:
v = np.array([[1],[2],[3]])

v

array([[1],
       [2],
       [3]])

### 2 - Matrix

In [8]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension ----->        .
1st dimension ----->        ._______.

2nd dimension ----->        .____|____.

3rd dimension ----->.       .____|____.
                                /
4th dimension ----->        
.
.
.
nth dimension

In [ ]:
1080px

720 px

### 3 - Describe Matrix

In [10]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix.shape

(3, 3)

In [12]:
matrix.size

9

In [13]:
matrix.ndim

2

### 4 - Max and Min Values

In [14]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(np.max(matrix))

9


In [16]:
print(np.min(matrix))

1


In [17]:
print(np.max(matrix, axis = 0)) # columns

[7 8 9]


In [19]:
print(np.max(matrix, axis = 1)) # rows

[3 6 9]


In [21]:
# help(np.max)

In [22]:
print(np.max(matrix, axis=1)[0])

3


### 5 - Statistics

In [ ]:
1 - Descriptive - mean, median, mode, standard deviation, variance, IQR, percentile

2 - Inferential - models, hypothesis testing, regression(relationship)

In [23]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(np.mean(matrix))

5.0


In [25]:
print(np.std(matrix))

2.581988897471611


In [26]:
print(np.var(matrix))

6.666666666666667


### 6 - Reshaping arrays

In [27]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [29]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [30]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [31]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]



### 7 - Selecting Elements

In [33]:
#            -7 -6 -5 -4 -3 -2 -1
v = np.array([11,12,13,14,15,16,17])
#            0  1  2   3  4  5  6

print(v[0])

11


In [34]:
print(v[5])

16


In [35]:
print(v[-1])

17


In [36]:
print(v[3:6])

[14 15 16]


In [37]:
print(v[2:5])

[13 14 15]


In [38]:
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
00  01  02
10  11  12
20  21  22

In [40]:
print(matrix[0,0])

1


In [41]:
print(matrix[2,1])

8


### 8 - Random Values

In [43]:
np.random.randint(0,11,5)

array([1, 0, 8, 7, 6])

In [45]:
np.random.randint(0,11,9)

array([ 3,  7,  8,  1,  4,  1, 10,  2,  6])

In [47]:
np.random.randint(0,11,9).reshape(3,3)

array([[3, 2, 3],
       [6, 3, 8],
       [0, 6, 8]])

In [50]:
np.random.seed(5)

np.random.randint(0,11,3)

array([3, 6, 6])